apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: rulebricks-hpa
  namespace: {{ .Release.Namespace }}
  annotations:
    description: "Automatically scales the Next.js UI based on resource usage"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: rulebricks-app
  minReplicas: 1
  maxReplicas: 3  # UI doesn't need many replicas
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60  # Wait 1 minute before scaling up
      policies:
        - type: Pods
          value: 1
          periodSeconds: 60  # Add at most 1 pod per minute
    scaleDown:
      stabilizationWindowSeconds: 300  # Wait 5 minutes before scaling down
      policies:
        - type: Pods
          value: 1
          periodSeconds: 60  # Remove at most 1 pod per minute
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70  # Scale up at 70% CPU
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80  # Scale up at 80% memory
