apiVersion: v1
kind: Service
metadata:
  name: rulebricks-rulebricks-chart
  namespace: rulebricks
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  selector:
    app: rulebricks-app
