apiVersion: apps/v1
kind: Deployment
metadata:
  name: rulebricks-app
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: rulebricks-app
  template:
    metadata:
      labels:
        app: rulebricks-app
    spec:
      imagePullSecrets:
        - name: regcred
      {{- with .Values.app.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.app.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: rulebricks-app
          image: {{ .Values.app.image.repository }}:{{ .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.app.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          resources:
            requests:
              cpu: "256m"
              memory: "256Mi"
            limits:
              cpu: "512m"
              memory: "1Gi"
          livenessProbe:
            httpGet:
              path: {{ .Values.app.livenessProbe.httpGet.path | default "/" }}
              port: {{ .Values.app.livenessProbe.httpGet.port }}
            initialDelaySeconds: {{ .Values.app.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.app.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.app.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.app.livenessProbe.failureThreshold }}
          readinessProbe:
            httpGet:
              path: {{ .Values.app.readinessProbe.httpGet.path | default "/api/health" }}
              port: {{ .Values.app.readinessProbe.httpGet.port }}
            initialDelaySeconds: {{ .Values.app.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.app.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.app.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.app.readinessProbe.failureThreshold }}
          env:
            - name: LICENSE_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: LICENSE_KEY
            - name: EMAIL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: EMAIL
            - name: UPSTASH_REDIS_REST_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: KV_REST_API_URL
            - name: UPSTASH_REDIS_REST_TOKEN
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: KV_REST_API_TOKEN
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets
