{{- $host0 := index .Values.ingress.hosts 0 -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: {{ .Release.Namespace }}
data:
  {{- $protocol := ternary "https" "http" .Values.app.tlsEnabled }}
  {{- $routerEntrypoint := ternary "websecure" "web" .Values.app.tlsEnabled }}
  PROTOCOL: {{ $protocol | quote }}
  DOMAIN_NAME: {{ $host0.host | quote }}
  ROUTER_ENTRYPOINT: {{ $routerEntrypoint | quote }}
  SUPABASE_PUBLIC_KEY: {{ .Values.app.supabaseAnonKey | default "" | quote }}
  SUPABASE_SECRET_KEY: {{ .Values.app.supabaseServiceKey | default "" | quote }}
  SUPABASE_URL: {{ .Values.app.supabaseUrl | default "" | quote }}
  NEXT_PUBLIC_EMAIL: {{ .Values.app.email | default "" | quote }}
  NEXT_PUBLIC_PROTOCOL: {{ $protocol | quote }}
  NEXT_PUBLIC_DOMAIN_NAME: {{ $host0.host | quote }}
  NEXT_PUBLIC_SUPABASE_URL: {{ .Values.app.supabaseUrl | default "" | quote }}
  NEXT_PUBLIC_SUPABASE_PUBLIC_KEY: {{ .Values.app.supabaseAnonKey | default "" | quote }}
  SELF_HOSTED: "1"
  NEXT_PUBLIC_SELF_HOSTED: "1"
  NEXT_PUBLIC_SANITY_PROJECT_ID: "0tthc473"
  SANITY_PROJECT_ID: "0tthc473"
  SANITY_API_DATASET: "production"
  KV_REST_API_URL: {{ printf "http://serverless-redis-http.%s" .Release.Namespace | quote }}
  KV_REST_API_TOKEN: "local_redis"
  NODE_ENV: "production"
  ENVIRONMENT: "production"
  NODE_OPTIONS: "--dns-result-order=ipv4first"
  {{- if .Values.app.smtp }}
  SMTP_HOST: {{ .Values.app.smtp.host | default "" | quote }}
  SMTP_PORT: {{ .Values.app.smtp.port | default "" | quote }}
  SMTP_USER: {{ .Values.app.smtp.user | default "" | quote }}
  SMTP_PASS: {{ .Values.app.smtp.pass | default "" | quote }}
  SMTP_FROM: {{ .Values.app.smtp.from | default "" | quote }}
  SMTP_FROM_NAME: {{ .Values.app.smtp.fromName | default "" | quote }}
  {{- end }}
  {{- if .Values.app.ai }}
  {{- if .Values.app.ai.enabled }}
  NEXT_PUBLIC_AI_ENABLED: "1"
  OPENAI_API_KEY: {{ .Values.app.ai.openaiApiKey | default "" | quote }}
  {{- end }}
  {{- end }}
  {{- if .Values.app.logging }}
  {{- if .Values.app.logging.enabled }}
  KAFKA_ENABLED: "1"
  KAFKA_BROKERS: {{ .Values.app.logging.kafkaBrokers | default "" | quote }}
  KAFKA_TOPIC: {{ .Values.app.logging.kafkaTopic | default "logs" | quote }}
  NEXT_PUBLIC_LOGGING_DESTINATION: {{ .Values.app.logging.loggingDestination | default "" | quote }}
  {{- end }}
  {{- end }}
