{{- if and .Values.hps .Values.hps.enabled .Values.app.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: rulebricks-hps
  namespace: {{ .Release.Namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: rulebricks-hps
  minReplicas: {{ .Values.hps.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.hps.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.hps.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.hps.autoscaling.targetMemoryUtilizationPercentage }}
  behavior:
    scaleUp:
      stabilizationWindowSeconds: {{ .Values.hps.autoscaling.behavior.scaleUp.stabilizationWindowSeconds }}
      policies:
      {{- range .Values.hps.autoscaling.behavior.scaleUp.policies }}
      - type: {{ .type }}
        value: {{ .value }}
        periodSeconds: {{ .periodSeconds }}
      {{- end }}
    scaleDown:
      stabilizationWindowSeconds: {{ .Values.hps.autoscaling.behavior.scaleDown.stabilizationWindowSeconds }}
      policies:
      {{- range .Values.hps.autoscaling.behavior.scaleDown.policies }}
      - type: {{ .type }}
        value: {{ .value }}
        periodSeconds: {{ .periodSeconds }}
      {{- end }}
{{- end }}
