{{- if and .Values.hps .Values.hps.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: rulebricks-hps
  namespace: {{ .Release.Namespace }}
  labels:
    app: rulebricks-hps
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: rulebricks-hps
{{- end }}
