apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.imageCredentials.name }}"
  namespace: rulebricks
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: "{{ template "rulebricks-chart.imagePullSecret" . }}"
