apiVersion: v1
kind: Service
metadata:
  name: serverless-redis-http
  namespace: rulebricks
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: serverless-redis-http
