apiVersion: apps/v1
kind: Deployment
metadata:
  name: serverless-redis-http
  namespace: rulebricks
spec:
  replicas: 1
  selector:
    matchLabels:
      app: serverless-redis-http
  template:
    metadata:
      labels:
        app: serverless-redis-http
    spec:
      containers:
        - name: serverless-redis-http
          image: hiett/serverless-redis-http:latest
          ports:
            - containerPort: 80
          env:
            - name: SRH_MODE
              value: "env"
            - name: SRH_TOKEN
              value: "local_redis"
            - name: SRH_CONNECTION_STRING
              value: "redis://redis:6379"
