name: Release Charts

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: 'v3.13.0'

      - name: Get Current Version
        id: current_version
        run: |
          # Get the latest tag or use 0.0.0
          LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          CURRENT_VERSION=${LATEST_TAG#v}
          echo "CURRENT_VERSION=${CURRENT_VERSION}" >> $GITHUB_OUTPUT
          echo "📌 Current version: ${CURRENT_VERSION}"

      - name: Calculate Next Version
        id: next_version
        run: |
          CURRENT="${{ steps.current_version.outputs.CURRENT_VERSION }}"

          # Split version into parts
          IFS='.' read -r MAJOR MINOR PATCH <<< "$CURRENT"

          # Increment patch version
          PATCH=$((PATCH + 1))

          NEXT_VERSION="${MAJOR}.${MINOR}.${PATCH}"
          echo "NEXT_VERSION=${NEXT_VERSION}" >> $GITHUB_OUTPUT
          echo "📈 Next version: ${NEXT_VERSION}"

      - name: Update Chart Versions
        run: |
          VERSION="${{ steps.next_version.outputs.NEXT_VERSION }}"

          # Update rulebricks chart
          sed -i "s/^version:.*/version: ${VERSION}/" charts/rulebricks/Chart.yaml
          sed -i "s/^appVersion:.*/appVersion: \"${VERSION}\"/" charts/rulebricks/Chart.yaml

          # Update supabase chart
          sed -i "s/^version:.*/version: ${VERSION}/" charts/supabase/Chart.yaml
          sed -i "s/^appVersion:.*/appVersion: \"${VERSION}\"/" charts/supabase/Chart.yaml

      - name: Package Charts
        run: |
          VERSION="${{ steps.next_version.outputs.NEXT_VERSION }}"

          # Create build directory
          mkdir -p build

          # Package individual charts
          helm package charts/rulebricks --destination build
          helm package charts/supabase --destination build

          # Create checksums
          cd build
          for chart in *.tgz; do
            sha256sum "$chart" > "$chart.sha256"
          done
          cd ..

          # List built artifacts
          echo "📦 Built charts:"
          ls -la build/

      - name: Create Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERSION="${{ steps.next_version.outputs.NEXT_VERSION }}"

          # Create release notes
          cat > release-notes.md << EOF
          # Release ${VERSION}

          ## 📦 Charts

          - rulebricks-${VERSION}.tgz
          - supabase-${VERSION}.tgz

          ## 🚀 Installation

          \`\`\`bash
          # Using Rulebricks CLI
          rulebricks upgrade --version ${VERSION}

          # Using Helm directly
          helm repo add rulebricks https://github.com/rulebricks/charts/releases/download/v${VERSION}
          helm repo update
          helm install rulebricks rulebricks/rulebricks --version ${VERSION}
          helm install supabase rulebricks/supabase --version ${VERSION}
          \`\`\`

          ## 📋 Checksums

          Verify downloaded files with the provided .sha256 files.
          EOF

          # Create GitHub release
          gh release create "v${VERSION}" \
            --title "Charts v${VERSION}" \
            --notes-file release-notes.md \
            build/*.tgz \
            build/*.sha256

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: charts-${{ steps.next_version.outputs.NEXT_VERSION }}
          path: |
            build/*.tgz
            build/*.sha256
          retention-days: 90

      - name: Create Helm Repository Index
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERSION="${{ steps.next_version.outputs.NEXT_VERSION }}"

          # Create repo directory
          mkdir -p repo
          cp build/*.tgz repo/

          # Generate index.yaml
          helm repo index repo --url "https://github.com/rulebricks/charts/releases/download/v${VERSION}"

          # Upload index.yaml to release
          gh release upload "v${VERSION}" repo/index.yaml --clobber

      - name: Summary
        run: |
          VERSION="${{ steps.next_version.outputs.NEXT_VERSION }}"

          echo "## 🎉 Release Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- **Version**: ${VERSION}" >> $GITHUB_STEP_SUMMARY
          echo "- **Tag**: v${VERSION}" >> $GITHUB_STEP_SUMMARY
          echo "- **Release URL**: https://github.com/rulebricks/charts/releases/tag/v${VERSION}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### 📦 Artifacts" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Chart | Size |" >> $GITHUB_STEP_SUMMARY
          echo "|-------|------|" >> $GITHUB_STEP_SUMMARY
          for chart in build/*.tgz; do
            name=$(basename "$chart")
            size=$(du -h "$chart" | cut -f1)
            echo "| $name | $size |" >> $GITHUB_STEP_SUMMARY
          done
